- name: Install backup script for {{ service_name }}
  template:
    src: borg.sh.j2
    dest: "{{ systemd_script_target }}/automatic-backup-{{ service_name }}.sh"
    owner: "{{ borg_systemd_user }}"
    group: "{{ borg_systemd_group }}"
    mode: "{{ systemd_script_mode }}"
- name: Install systemd service for repository {{ service_name }}
  template:
    src: automatic-backup.service.j2
    dest: "{{ systemd_target_dir }}/automatic-backup-{{ service_name }}.service"
    mode: "{{ systemd_service_mode }}"
- name: Install systemd timer for repository {{ service_name }}
  template:
    src: automatic-backup.timer.j2
    dest: "{{ systemd_target_dir }}/automatic-backup-{{ service_name }}.timer"
    mode: "{{ systemd_service_mode }}"
- name: enable a timer automatic backup
  systemd:
    name: automatic-backup-{{ service_name }}.timer
    state: started
    enabled: yes